# Generated by Django 2.0.2 on 2018-02-13 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_todo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
    ]
