# Generated by Django 2.0.2 on 2018-02-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_todo_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Normal'), ('3', 'High')], default='2', max_length=6),
        ),
    ]
