# Generated by Django 2.0.2 on 2018-02-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_todo_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='title',
        ),
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.TextField(max_length=50),
        ),
    ]
