# Generated by Django 2.0.2 on 2018-02-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_auto_20180215_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
