# Generated by Django 2.0.2 on 2018-02-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0008_todo_completed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.TextField(max_length=140),
        ),
    ]
